extraction:
  cpp:
    prepare:
      packages:
        - libssl-dev
        - clang-10
    after_prepare:
      - curl -LO https://github.com/Kitware/CMake/releases/download/v3.19.5/cmake-3.19.5-Linux-x86_64.sh
      - chmod +x cmake-3.19.5-Linux-x86_64.sh
      - mkdir lcmake
      - ./cmake-3.19.5-Linux-x86_64.sh --prefix=lcmake --skip-license --exclude-subdir
      - export PATH=$PWD/lcmake/bin:$PATH